const menu = [
    {
      id: 1,
      title: 'Double Burger Meal',
      category: 'Burger',
      price: 16.99,
      img: '/images/menu/item-1.jpg',
      desc: `Two 100% beef patties with cheese, ketchup, mayonnaise, butter and mustard.`,
    },
    {
      id: 2,
      title: 'ATW Burger Meal',
      category: 'Burger',
      price: 17.99,
      img: '/images/menu/item-2.jpg',
      desc: `One 100% beef patty with cheese, onion, tomato, ketchup, mayonnaise, butter, mustard, and our special sauce.`,
    },
    {
      id: 3,
      title: 'Burger Buddies Meal',
      category: 'Burger',
      price: 35.99,
      img: '/images/menu/item-3.jpg',
      desc: `Two burgers with one 100% beef patty with cheese, onion, tomato, ketchup, mayonnaise, butter, mustard, and our special sauce.`,
    },
    {
      id: 4,
      title: 'Master Burger Meal',
      category: 'Burger',
      price: 18.99,
      img: '/images/menu/item-4.jpg',
      desc: `One100% beef patty burger with anything you want including curly fries and chili.`,
    },
    {
      id: 5,
      title: 'Simple Chicken Meal',
      category: 'Chicken',
      price: 14.99,
      img: '/images/menu/item-5.jpg',
      desc: `TFarm raised chicken patty with cheese, lettuce, tomato mayonnaise, and butter.`,
    },
    {
      id: 6,
      title: 'ATW Chicken Meal',
      category: 'Chicken',
      price: 15.99,
      img: '/images/menu/item-6.jpg',
      desc: `Two farm raised chicken patty burgers with cheese, lettuce, pickle, tomato and our special sauce.`,
    },
    {
      id: 7,
      title: 'Chicken Buddies Meal',
      category: 'Chicken',
      price: 29.99,
      img: '/images/menu/item-7.jpg',
      desc: `Two farm raised chicken patty burgers with cheese, lettuce and tomato.`,
    },
    {
      id: 8,
      title: 'Master Chicken Meal',
      category: 'Chicken',
      price: 16.99,
      img: '/images/menu/item-8.jpg',
      desc: `Farm raised chicken patty burger with anything you want including curly fries.`,
    },
    {
      id: 9,
      title: 'Glizzy Meal',
      category: 'Glizzy',
      price: 15.99,
      img: '/images/menu/item-9.jpg',
      desc: `A glizzy with anything you want including curly fries, and our special sauce.`,
    },
    {
      id: 10,
      title: 'Chizzy Meal',
      category: 'Glizzy',
      price: 15.99,
      img: '/images/menu/item-10.jpg',
      desc: `A glizzy with chili, your choice of cheese and any sauce you want.`,
    },
    {
      id: 11,
      title: 'Calizzy Meal',
      category: 'Glizzy',
      price: 15.99,
      img: '/images/menu/item-11.jpg',
      desc: `A 100% vegan glizzy with avocado and our special vegan sauce.`,
    },
    {
      id: 12,
      title: 'Phlizzy Meal',
      category: 'Glizzy',
      price: 15.99,
      img: '/images/menu/item-12.jpg',
      desc: `A  glizzy with onions, bell peppers, and mozarella cheese. `,
    },
  ];
  export default menu;
  